// In RootLayout.js (your layout component)
import { JetBrains_Mono } from "next/font/google";
import { Header } from "@/components/Header";
import PageTransition from "../components/PageTransition"; // Corrected import

import "./globals.css";
import StairTransition from "@/components/StairTransition";

// Import Google font with specific options
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrains-mono",
});

// Metadata for the page
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
